In [58]:
import pandas
import numpy

players_df = pandas.read_csv("./players.csv")
players_df

,no,country,name,peak_rating,peak_year,birth_year,world_champion,world_rapid,world_blitz,world_fisher,world_cup
0,1,Norway,Magnus Carlsen,2882,2014,1990,5,5,7,0,1
1,2,Russia,Garry Kasparov,2851,1999,1963,6,0,0,0,0
2,3,United States,Fabiano Caruana,2844,2014,1992,0,0,0,0,0
3,4,United States,Levon Aronian,2830,2014,1982,0,0,1,0,2
4,5,United States,Wesley So,2822,2017,1993,0,0,0,1,0
5,6,Azerbaijan,Shakhriyar Mamedyarov,2820,2018,1985,0,1,0,0,0
6,7,France,Maxime Vachier-Lagrave,2819,2016,1990,0,0,1,0,0
7,8-9,India,Viswanathan Anand,2817,2011,1969,5,1,0,0,0
8,8-9,Russia,Vladimir Kramnik,2817,2016,1975,3,0,0,0,1
9,10-12,Bulgaria,Veselin Topalov,2816,2015,1975,1,0,0,0,0
10,10-12,United States,Hikaru Nakamura,2816,2015,1987,0,0,0,1,0
11,10-12,China,Ding Liren,2816,2018,1992,1,0,0,0,0
12,13,Russia,Alexander Grischuk,2810,2014,1983,0,0,3,0,0
13,14,France,Alireza Firouzja,2804,2021,2003,0,0,0,0,0

In [59]:
players_df["world_titles"] = (
    players_df["world_champion"]
    + players_df["world_rapid"]
    + players_df["world_blitz"]
    + players_df["world_fisher"]
    + players_df["world_cup"]
)
players_df = players_df.sort_values(by=["world_titles", "peak_rating"], ascending=[False, True])
players_df

,no,country,name,peak_rating,peak_year,birth_year,world_champion,world_rapid,world_blitz,world_fisher,world_cup,world_titles
0,1,Norway,Magnus Carlsen,2882,2014,1990,5,5,7,0,1,18
7,8-9,India,Viswanathan Anand,2817,2011,1969,5,1,0,0,0,6
1,2,Russia,Garry Kasparov,2851,1999,1963,6,0,0,0,0,6
8,8-9,Russia,Vladimir Kramnik,2817,2016,1975,3,0,0,0,1,4
12,13,Russia,Alexander Grischuk,2810,2014,1983,0,0,3,0,0,3
3,4,United States,Levon Aronian,2830,2014,1982,0,0,1,0,2,3
9,10-12,Bulgaria,Veselin Topalov,2816,2015,1975,1,0,0,0,0,1
10,10-12,United States,Hikaru Nakamura,2816,2015,1987,0,0,0,1,0,1
11,10-12,China,Ding Liren,2816,2018,1992,1,0,0,0,0,1
6,7,France,Maxime Vachier-Lagrave,2819,2016,1990,0,0,1,0,0,1
5,6,Azerbaijan,Shakhriyar Mamedyarov,2820,2018,1985,0,1,0,0,0,1
4,5,United States,Wesley So,2822,2017,1993,0,0,0,1,0,1
13,14,France,Alireza Firouzja,2804,2021,2003,0,0,0,0,0,0
2,3,United States,Fabiano Caruana,2844,2014,1992,0,0,0,0,0,0

In [60]:
players_df["achieved_age"] = players_df["peak_year"] - players_df["birth_year"]
players_df["achieved_age_range"] = numpy.floor(players_df["achieved_age"] / 10) * 10
players_df["achieved_decade"] = numpy.floor(players_df["peak_year"] / 10) * 10
players_df = players_df.sort_values(by=["achieved_age", "peak_rating"], ascending=[True, False])
players_df

,no,country,name,peak_rating,peak_year,birth_year,world_champion,world_rapid,world_blitz,world_fisher,world_cup,world_titles,achieved_age,achieved_age_range,achieved_decade
13,14,France,Alireza Firouzja,2804,2021,2003,0,0,0,0,0,0,18,10.0,2020.0
2,3,United States,Fabiano Caruana,2844,2014,1992,0,0,0,0,0,0,22,20.0,2010.0
0,1,Norway,Magnus Carlsen,2882,2014,1990,5,5,7,0,1,18,24,20.0,2010.0
4,5,United States,Wesley So,2822,2017,1993,0,0,0,1,0,1,24,20.0,2010.0
6,7,France,Maxime Vachier-Lagrave,2819,2016,1990,0,0,1,0,0,1,26,20.0,2010.0
11,10-12,China,Ding Liren,2816,2018,1992,1,0,0,0,0,1,26,20.0,2010.0
10,10-12,United States,Hikaru Nakamura,2816,2015,1987,0,0,0,1,0,1,28,20.0,2010.0
12,13,Russia,Alexander Grischuk,2810,2014,1983,0,0,3,0,0,3,31,30.0,2010.0
3,4,United States,Levon Aronian,2830,2014,1982,0,0,1,0,2,3,32,30.0,2010.0
5,6,Azerbaijan,Shakhriyar Mamedyarov,2820,2018,1985,0,1,0,0,0,1,33,30.0,2010.0
1,2,Russia,Garry Kasparov,2851,1999,1963,6,0,0,0,0,6,36,30.0,1990.0
9,10-12,Bulgaria,Veselin Topalov,2816,2015,1975,1,0,0,0,0,1,40,40.0,2010.0
8,8-9,Russia,Vladimir Kramnik,2817,2016,1975,3,0,0,0,1,4,41,40.0,2010.0
7,8-9,India,Viswanathan Anand,2817,2011,1969,5,1,0,0,0,6,42,40.0,2010.0

In [61]:
countries = players_df["country"].value_counts()
countries

country
United States    4
Russia           3
France           2
Norway           1
China            1
Azerbaijan       1
Bulgaria         1
India            1
Name: count, dtype: int64